Update package dependencies, improve error handling, and fix documentation
google/generative-ai-go pull request #58
Opened 2024-02-29 06:47 UTC by kasugamirai

Upgraded Go from version 1.21 to 1.22 and updated various indirect dependencies. Error handling in client_test.go has been enhanced by using the errors.Is function for comparison instead of direct equality check. Fixed minor typos and inconsistencies in the comments of client.go and embed.go.

2024-02-29 16:56 UTC, jba requested changes
Thanks for your contribution! 

We will accept the documentation fixes. I've commented on other aspects of this PR.

2024-02-29 16:56 UTC, jba commented on genai/client_test.go
> +	defer func(client *Client) {
We don't usually check the result of client.Close; it isn't really actionable. An error here doesn't affect anything, since the service is stateless.

2024-02-29 16:56 UTC, jba commented on genai/client_test.go
> +					if errors.Is(err, iterator.Done) {
Normally this is a good change. But we are following these [iterator guidelines](https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines#the-next-method), which guarantees that the error is actually `iterator.Done`. So using `==` here is fine.

2024-02-29 16:56 UTC, jba commented on go.mod
> +go 1.22
We'd like to support the most recent two versions of Go. That is the Go team's standard policy.

2024-02-29 20:24 UTC, jba requested changes

2024-02-29 20:24 UTC, jba commented on go.mod
>  require (
How did you get this change? From `go mod tidy`? I wonder where the go-logr dependencies came from? They weren't there before.

I think we should remove these changes from this PR and do another one that is just the result of `go mod tidy`.

2024-03-01 09:25 UTC, kasugamirai commented
Thanks for your suggestion

2024-03-01 14:31 UTC, jba approved these changes
Thanks!

2024-03-01 15:34 UTC, merged